### ISSUE TITLE
how to use various methods in the jupyter notebook

### ISSUE THREAD

**Issue by heemokyim** [shubhomoydas/ad_examples#7]
I'm trying to use your code in Jupyter notebook's Python kernel. 
I only know how to install using pip, can you tell me how to use it?

**Comment by shubhomoydas** [comment]
Here is example code you can copy-paste into jupyter notebook. This is code from demo_aad.py. I assume that you have pip-installed ad_examples in whichever python environment (virtual or not) you are running jupyter.
===========================

import logging
import numpy as np

from ad_examples.common.gen_samples import get_synthetic_samples
from ad_examples.aad.aad_support import AadOpts, get_aad_command_args, configure_logger
from ad_examples.aad.forest_description import CompactDescriber, MinimumVolumeCoverDescriber, \
    BayesianRulesetsDescriber, get_region_memberships

from ad_examples.aad.demo_aad import get_debug_args, detect_anomalies_and_describe

logger = logging.getLogger(__name__)

# Prepare the aad arguments. It is easier to first create the parsed args and
# then create the actual AadOpts from the args
args = get_aad_command_args(debug=True, debug_args=get_debug_args())

# configure_logger(args)  # create a ./temp folder in case you need debug logs

opts = AadOpts(args)
logger.debug(opts.str_opts())

np.random.seed(opts.randseed)

# load synthetic (toy 2) dataset
x, y = get_synthetic_samples(stype=2)

# run interactive anomaly detection loop
model, x_transformed, queried, ridxs_counts, region_extents = detect_anomalies_and_describe(x, y, opts)
