### ISSUE TITLE
Fixed imports for test_add notebook

### ISSUE THREAD

**Issue by ninashamsi01** [shubhomoydas/ad_examples#9]
Hello, 

Below is the code for fixing import issues within the test_aad ipython notebook. 

    `import logging
     import numpy as np

    from ad_examples.common.gen_samples import get_synthetic_samples
    from ad_examples.aad.forest_description import CompactDescriber, MinimumVolumeCoverDescriber, \
    BayesianRulesetsDescriber, get_region_memberships
    from ad_examples.aad.aad_globals import AadOpts, get_aad_command_args
    from ad_examples.aad.demo_aad import get_debug_args, detect_anomalies_and_describe
    from ad_examples.common.utils import configure_logger

    logger = logging.getLogger(__name__)

    # Prepare the aad arguments. It is easier to first create the parsed args and
    # then create the actual AadOpts from the args
    args = get_aad_command_args(debug=True, debug_args=get_debug_args())

    # configure_logger(args)  # create a ./temp folder in case you need debug logs
    opts = AadOpts(args)
    logger.debug(opts.str_opts())

    np.random.seed(opts.randseed)

    # load synthetic (toy 2) dataset
    x, y = get_synthetic_samples(stype=2)

    # run interactive anomaly detection loop
    model, x_transformed, queried, ridxs_counts, region_extents = detect_anomalies_and_describe(x, y, opts)`

**Comment by shubhomoydas** [comment]
Thanks for reporting this ninashamsi01. I have checked in the fix.
